### ISSUE TITLE
First Alpha Release - 2.0.0.dev2

### ISSUE THREAD

**Issue by BobDenny** [ASCOMInitiative/alpyca#1]
This is the first release of Alpyca, so it is guaranteed to have 'issues'.  This list is where you can file issues and suggest patches. 

Please don't ask programming questions here. Instead post to the [ASCOM Driver and Application Development Support Forum](https://ascomtalk.groups.io/g/Developer).  Thanks.

**Comment by moemyself3** [comment]
Hi @BobDenny ! I've been following the alpaca+python movement for a bit since I want to implement the use of python for a remote survey observatory soon. I'd recommend using a release tag to mark the release to avoid having an unnecessary open issue. (I hope to be able to contribute as well!)

 https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by BobDenny** [comment]
The first (-devx) versions are pre-releases. I am about to release the first real version 2.0.1rc1 and it will be listed here as a release.  Thank you!!
